// import m1 from '../assets/monsters/monster1.png'; 
// import c2 from '../assets/coins/c2.png'; 
// import c3 from '../assets/coins/c3.png'; 
// import c4 from '../assets/coins/c4.png'; 
// import c6 from '../assets/coins/logo-coin6.png'; 
// import goldcoin from '../assets/coins/gold-coin.png'; 
// import orangecoin from '../assets/coins/orange-coin.png'; 
// import usd1 from '../assets/coins/usd1.png'; 
// import usdcoin from '../assets/coins/usd-coin.png'; 
// import friend from '../assets/icons/add-friend.png'; 
// import goal from '../assets/icons/goal.png';
// import energy from '../assets/icons/energy.png';
// import speed from '../assets/icons/speed.png';
// import rocket from '../assets/icons/rocket.png';
// import thunder from '../assets/icons/thunder.png';
// import piechart from '../assets/icons/pie-chart.png';

// import mine from '../assets/icons/mine.png';
// import normal from '../assets/icons/normal.png';
// import fire from '../assets/icons/fire.png';
// import water from '../assets/icons/water.png';
// import electric from '../assets/icons/electric.png';
// import grass from '../assets/icons/grass.png';
// import ice from '../assets/icons/ice.png';
// import fighting from '../assets/icons/fighting.png';
// import poison from '../assets/icons/poison.png';
// import ground from '../assets/icons/ground.png';
// import flying from '../assets/icons/flying.png';
// import psychic from '../assets/icons/psychic.png';
// import bug from '../assets/icons/bug.png';
// import rock from '../assets/icons/rock.png';
// import ghost from '../assets/icons/ghost.png';
// import dragon from '../assets/icons/dragon.png';
// import dark from '../assets/icons/dark.png';
// import steel from '../assets/icons/steel.png';
// import fairy from '../assets/icons/fairy.png';
// import rightArrow from '../assets/icons/right-arrow.png';
// import logoWithoutWord from '../assets/logo.png';
// import firebow from '../assets/weapons/fire/firebow.jpg';

// export default {
//     firebow, c2,c3,c4, c6,goldcoin, orangecoin, usdcoin, friend, goal, rocket, piechart, thunder, energy, speed, usd1, mine, normal, fire, water, electric, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, ghost, dragon, dark, steel, fairy, rightArrow, m1, logoWithoutWord
// };  

import assets_logo from '../assets/logo.png';
import monsters_m1 from '../assets/monsters/m1.png';
import monsters_coin1 from '../assets/monsters/coin1.png';
import monsters_monster1 from '../assets/monsters/monster1.png';
import monsters_1 from '../assets/monsters/1.png';
import coins_gold_coin from '../assets/coins/gold-coin.png';
import coins_logo_coin8 from '../assets/coins/logo-coin8.png';
import coins_c4 from '../assets/coins/c4.png';
import coins_c1 from '../assets/coins/c1.png';
// import coins_orange_coin from '../assets/coins/orange-coin.jpg';
import coins_c2 from '../assets/coins/c2.png';
import coins_usd1 from '../assets/coins/usd1.png';
// import coins_usd_coin from '../assets/coins/usd-coin.jpg';
import coins_c3 from '../assets/coins/c3.png';
import coins_logo_coin7 from '../assets/coins/logo-coin7.png';
import coins_orange_coin from '../assets/coins/orange-coin.png';
import coins_logo_coin6 from '../assets/coins/logo-coin6.png';
import coins_usd_coin from '../assets/coins/usd-coin.png';
import coins_c5 from '../assets/coins/c5.png';
import coins_logo_coin9 from '../assets/coins/logo-coin9.png';
import bg_roadmap14 from '../assets/bg/roadmap14.png';
import bg_roadmap13 from '../assets/bg/roadmap13.png';
import bg_roadmap17 from '../assets/bg/roadmap17.png';
import bg_roadmap11 from '../assets/bg/roadmap11.png';
import bg_roadmap18 from '../assets/bg/roadmap18.png';
import bg_roadmap15 from '../assets/bg/roadmap15.png';
import bg_roadmap16 from '../assets/bg/roadmap16.png';
import bg_1 from '../assets/bg/1.png';
import bg_2 from '../assets/bg/2.png';
import bg_roadmap12 from '../assets/bg/roadmap12.png';
import icons_speed from '../assets/icons/speed.png';
import icons_add_friend from '../assets/icons/add-friend.png';
import icons_thunder from '../assets/icons/thunder.png';
import icons_psychic from '../assets/icons/psychic.png';
import icons_energy from '../assets/icons/energy.png';
import icons_poison from '../assets/icons/poison.png';
import icons_steel from '../assets/icons/steel.png';
import icons_rocket from '../assets/icons/rocket.png';
import icons_fairy from '../assets/icons/fairy.png';
import icons_ground from '../assets/icons/ground.png';
import icons_dragon from '../assets/icons/dragon.png';
import icons_goal from '../assets/icons/goal.png';
import icons_dark from '../assets/icons/dark.png';
import icons_mine from '../assets/icons/mine.png';
import icons_fighting from '../assets/icons/fighting.png';
import icons_electric from '../assets/icons/electric.png';
import icons_grass from '../assets/icons/grass.png';
import icons_right_arrow from '../assets/icons/right-arrow.png';
import icons_fire from '../assets/icons/fire.png';
import icons_rock from '../assets/icons/rock.png';
import icons_share from '../assets/icons/share.png';
import icons_pie_chart from '../assets/icons/pie-chart.png';
import icons_ghost from '../assets/icons/ghost.png';
import icons_flying from '../assets/icons/flying.png';
import icons_normal from '../assets/icons/normal.png';
import icons_ice from '../assets/icons/ice.png';
import icons_bug from '../assets/icons/bug.png';
import icons_water from '../assets/icons/water.png';
import fire_firebow from '../assets/weapons/fire/firebow.jpg';

export default {
assets_logo, monsters_m1, monsters_coin1, monsters_monster1, monsters_1, coins_gold_coin, coins_logo_coin8, coins_c4, coins_c1,  coins_c2, coins_usd1, coins_usd_coin, coins_c3, coins_logo_coin7, coins_orange_coin, coins_logo_coin6, coins_c5, coins_logo_coin9, bg_roadmap14, bg_roadmap13, bg_roadmap17, bg_roadmap11, bg_roadmap18, bg_roadmap15, bg_roadmap16, bg_1, bg_2, bg_roadmap12, icons_speed, icons_add_friend, icons_thunder, icons_psychic, icons_energy, icons_poison, icons_steel, icons_rocket, icons_fairy, icons_ground, icons_dragon, icons_goal, icons_dark, icons_mine, icons_fighting, icons_electric, icons_grass, icons_right_arrow, icons_fire, icons_rock, icons_share, icons_pie_chart, icons_ghost, icons_flying, icons_normal, icons_ice, icons_bug, icons_water, fire_firebow
};